README.md

verifying the toAddress makes more sense then verifying the fromAddress

change fromAddress to toAddress in readme example

---

src/resources/base.js
src/resources/shipment.js
test/helpers/apiStub.js
test/resources/shipment.js

Update convertlabelformat to use GET instead of POST

---

src/resources/order.js
src/resources/shipment.js
test/resources/order.js

For https://github.com/EasyPost/easypost-node/issues/52

fix orders shipments parsing + getRates

---

src/resources/batch.js
test/resources/batch.js

Add batch.buy

---

src/resources/pickup.js

Add batch id, update carrieraccount type for pickups

---

src/resources/insurance.js
src/resources/pickup.js
src/resources/shipment.js
src/resources/tracker.js

for https://github.com/EasyPost/easypost-node/issues/71

add reference field to insurance, shipment, pickup, and tracker

---

src/resources/apiKey.js
test/resources/apiKey.js

This was improperly reducing, and created nested arrays.

Fix api key child mapping

---

package.json
src/resources/carrierAccount.js

Fixes https://github.com/EasyPost/easypost-node/issues/82

CarrierAccounts.retrieve + .save

---

package-lock.json

Patched security vulnerabilities in package-lock.json compliments of GitHub's weekly email.

Security updates to package-lock.json

---

src/easypost.js
src/resources/rate.js
test/resources/rate.js

Added the missing rate object allowing rates to be retrieved - all other CL's allow this.

Added rate object and tests

---

examples/addresses/create-address.js
examples/addresses/retrieve-addresses.js
examples/api-keys/retrieve-api-keys.js
examples/batches/add-shipment-to-batch.js
examples/batches/create-batch.js
examples/batches/generate-batch-label.js
examples/batches/retrieve-batch.js
examples/carriers/delete-carrier-account.js
examples/orders/buy-order.js
examples/orders/create-order.js
examples/parcels/create-parcel.js
examples/pickups/buy-pickup.js
examples/pickups/create-pickup.js
examples/reports/create-reports.js
examples/scanforms/create-scanform.js
examples/scanforms/retrieve-scanform.js
examples/scanforms/retrieve-scanforms.js
examples/shipments/buy-shipment.js
examples/shipments/convert-label.js
examples/shipments/create-shipment.js
examples/trackers/retrieve-trackers.js
examples/webhooks/create-webhook.js
examples/webhooks/delete-webhook.js
examples/webhooks/retrieve-webhook.js
examples/webhooks/retrieve-webhooks.js
examples/webhooks/update-webhook.js

Added various code examples for those that find the CL and want to know how methods could be called and used.

Added various code examples

---

src/easypost.js
src/resources/event.js
test/resources/event.js

Added missing events object and tests allowing to retrieve one or many events.

Added missing event object

---

CHANGELOG.md

Corrects release date in CHANGELOG

corrects release date in CHANGELOG

---

README.md

Adds missing lint instructions to README

chore: add lint instructions to README

---

.gitignore
CHANGELOG.md
examples/trackers/create-list.js
src/resources/tracker.js
test/resources/tracker.js

Add functionality to create trackers in bulk for our node library.
Currently, our node library is missing one of the core features.
Add CreateList method in Tracker class.
Add a unit test in tracker.js test file.

Create list tracker

---

CHANGELOG.md
examples/users/update-brand.js
src/resources/brand.js
src/resources/user.js

Added support for updating the user brand in the Node Library, updated the changelog, and add code example.
This is one of the missing core features.
Added **updateBrand()** method in User class and add a new file for a code example. Created a new class for Brand.
E2E local testing, no unit test was written because there is my personal information in the cassette.

add support for update_brand.

---

test/cassettes/Shipment-Resource_2534528937/creates-a-shipment-with-empty-or-null-objects-and-arrays_3556538065/recording.har
test/resources/shipment.test.js

This PR adds a missing assertion for `tax_identifiers`

add assertion for tax_identifiers.

---

CHANGELOG.md
src/resources/address.js
test/cassettes/Address-Resource_3542783961/creates-a-verified-address_2691107999/recording.har
test/cassettes/Address-Resource_3542783961/verifies-an-address_2951018147/recording.har
test/helpers/fixture.js
test/resources/address.test.js

Adds `verifyAddress` and `createAndVerify` functions like other libs have.

feat: add verifyAddress and createAndVerify Functions

---

CHANGELOG.md
src/resources/address.js
src/resources/batch.js
test/cassettes/Batch-Resource_4123662849/creates-and-buys-a-batch-in-a-single-call_1654959317/recording.har
test/resources/batch.test.js

- Adds `Batch.createAndBuy()` function like we have in other libs.

feat: adds Batch.createAndBuy function

---

src/easypost.js

Removes unused `patch` HTTP method in this project
NA

chore: remove unused patch HTTP function

---

CHANGELOG.md
package-lock.json
package.json
src/resources/order.js
src/resources/pickup.js
src/resources/shipment.js
src/resources/util.js
test/cassettes/Order-Resource_86685445/gets-the-lowest-rate_906620131/recording.har
test/cassettes/Pickup-Resource_1673862587/buys-a-pickup_1934475561/recording.har
test/cassettes/Pickup-Resource_1673862587/cancels-a-pickup_4207662041/recording.har
test/cassettes/Pickup-Resource_1673862587/gets-the-lowest-rate_906620131/recording.har
test/cassettes/Pickup-Resource_1673862587/retrieves-a-pickup_3320623723/recording.har
test/cassettes/Shipment-Resource_2534528937/gets-the-lowest-rate_906620131/recording.har
test/cassettes/Shipment-Resource_2534528937/gets-the-lowest-smartrate-from-a-list-of-smartrates_2148185914/recording.har
test/cassettes/Shipment-Resource_2534528937/gets-the-lowest-smartrate_175702804/recording.har
test/cassettes/Shipment-Resource_2534528937/raises-an-error-for-getLowestSmartrate-when-no-rates-are-found-due-to-deliveryAccuracy_3282317757/recording.har
test/cassettes/Shipment-Resource_2534528937/raises-an-error-for-getLowestSmartrate-when-no-rates-are-found-due-to-deliveryDays_4238247347/recording.har
test/cassettes/Shipment-Resource_2534528937/raises-an-error-for-lowestSmartrate-when-no-rates-are-found-due-to-deliveryAccuracy_4259296465/recording.har
test/cassettes/Shipment-Resource_2534528937/raises-an-error-for-lowestSmartrate-when-no-rates-are-found-due-to-deliveryDays_4095457255/recording.har
test/common.js
test/helpers/fixture.js
test/resources/order.test.js
test/resources/pickup.test.js
test/resources/shipment.test.js

- Adds a `lowestRate` function to Orders and Pickups
- Adds a `Shipment.getLowestSmartrate()` and `shipment.lowest_smartrate()` functions

feat: adds lowest_rate to more objects

---

test/resources/beta/referral.test.js

Moves the referral test to a sub directory and removes a false positive assertion.

fix: referral test

---

CHANGELOG.md
package-lock.json
package.json

chore: prepare v5.2.0 for release

---

CHANGELOG.md
src/easypost.js
src/resources/credit_card.js
src/resources/payment_method.js
test/cassettes/PaymentMethod-Resource_823003072/retrieves-all-payment-methods_2987245065/recording.har
test/resources/credit_card.test.js
test/resources/payment_method.test.js

Adds PaymentMethod.all(), CreditCard.fund(), and CreditCard.delete() functions
Added unit test for retrieving all payment methods
Can't test CreditCard.fund and CreditCard.delete due to the lack of an available real credit card in the tests

add billing functions.

---

README.md

Adds new testing info to README.

docs: add test info to README

---

src/resources/payment_method.js

Add the missing conditional statement to check if the id is null when retrieving payment methods.

add missing conditional statement to check if there is a payment method.

---

.gitattributes

Ignore cassette diffs locally (line 1) and collapse on GitHub (line 2) for easier review.

chore: ignore cassette diffs via gitattributes

---

CHANGELOG.md
src/resources/webhook.js
test/helpers/fixture.js

- Add `webhook_secret` property to Webhook
- Update changelog
- No changes to unit tests
- All tests pass

Webhook secret support

---

test/resources/credit_card.test.js

changed CreditCardFund test from 20 to 2000

Update CreditCardFund test

---

CHANGELOG.md
src/easypost.js
test/helpers/setup_polly.js

Adds OS-specific details to the user-agent header

Adds OS-specific details to the user-agent header

---

CHANGELOG.md
package.json

chore: prepare v5.3.0 for release

---

package-lock.json
package.json

Pins Typescript correctly for our build matrix

fix: typescript version pinning

---

src/resources/shipment.js

lowercase `deliveryAccuracy` to avoid any uppercase that can cause a mismatch in the percentile.
N/A

lowercase deliveryAccuracy

---

src/resources/shipment.js
test/cassettes/Shipment-Resource_2534528937/generates-a-form-for-a-shipment_1612844164/recording.har
test/helpers/fixture.js
test/resources/shipment.test.js
types/Shipment/Shipment.d.ts

- Add function to generate a form for a shipment
- Add unit test and cassette

Generate a form for a shipment

---

CHANGELOG.md
package.json

chore: prepare v5.4.0 for release

---

.gitignore

chore: ignores env file

---

CHANGELOG.md
package.json

chore: prepares v5.5.0 for release

---

test/cassettes/Shipment-Resource_2534528937/buy-a-shipment-with-carbon-offset_4260710690/recording.har
test/cassettes/Shipment-Resource_2534528937/create-a-shipment-with-carbon-offset_989550468/recording.har
test/cassettes/Shipment-Resource_2534528937/one-call-buy-a-shipment-with-carbon-offset_2667011568/recording.har
test/resources/shipment.test.js

Corrects carbon offset tests to check that they are set correctly.
Updates tests to check that carbon offset is `undefined` instead of `null`.

fix: carbon offset tests

---

.github/workflows/ci.yml
Makefile
README.md
package.json

Adds a Makefile to the project in a uniform fashion like all other libs have. This Makefile uses the existing `npm` commands so that either/or will work.

chore: adds Makefile to project

---

test/cassettes/Shipment-Resource_2534528937/one-call-buy-a-shipment-with-carbon-offset_2667011568/recording.har
test/helpers/fixture.js
test/resources/shipment.test.js

chore: removes unused end_shipper fixture

---

test/helpers/fixture.js

Uses the new event-body fixture.

fix: use the new event-body fixture

---

CHANGELOG.md
package.json

chore: prepares v5.6.0 for release

---

CHANGELOG.md
package-lock.json
package.json

chore: prepares v5.6.1 for release

---

CHANGELOG.md
src/resources/shipment.js

- Adds support to pass `endShipperId` to the shipment buy call

feat: adds endShipperId to shipment buy call

---

CHANGELOG.md
package-lock.json
package.json

chore: prepares v5.7.0 for release

---

README.md
test/helpers/setup_polly.js

Expires cassettes after 6 months to ensure that data is recent within a half year. Warnings will be raised when cassettes expire.
Set an expiration of 10 days to test and warnings were thrown as expected

feat: expire cassettes after 6 months

---

README.md
src/easypost.js

Removes the browser check when building headers since this library out of the box cannot run in a browser.
We tested using this library in the browser which is not possible, leaving me with high confidence that this is legacy code that can be removed easily.

chore: remove browser check when building headers

---

CHANGELOG.md
package.json

chore: prepares v5.7.1 for release

---

.github/workflows/ci.yml
README.md

Adds coveralls to report code coverage

feat: adds coveralls

---

CHANGELOG.md
package.json

chore: prepare v5.8.0 for release

---

CHANGELOG.md
package.json

chore: prepare v5.9.0 for release

---

CHANGELOG.md
src/resources/pickup.js
test/cassettes/Pickup-Resource_1673862587/retrieves-all-pickup_1952424459/recording.har
test/resources/pickup.test.js

add retrieve all pickups
add a unit test

add retrieve all pickups

---

.eslintignore
package-lock.json
src/resources/referral.js
types/Billing/Billing.d.ts
types/Brand/Brand.d.ts
types/Brand/index.d.ts
types/CarbonOffset/CarbonOffset.d.ts
types/CarbonOffset/index.d.ts
types/Customs/CustomsInfo/CustomsInfo.d.ts
types/Customs/CustomsInfo/CustomsInfoCreateParameters.d.ts
types/Customs/CustomsItem/CustomsItem.d.ts
types/Customs/CustomsItem/CustomsItemCreateParameters.d.ts
types/EasyPost.d.ts
types/Rate/Rate.d.ts
types/Rate/index.d.ts
types/Referral/Referral.d.ts
types/Referral/ReferralCreateParameters.d.ts
types/Referral/ReferralListParameters.d.ts
types/ScanForm/ScanForm.d.ts
types/ScanForm/ScanFormCreateParameters.d.ts
types/ScanForm/ScanFormListParameters.d.ts
types/Shipment/Shipment.d.ts
types/Tracker/Tracker.d.ts
types/User/User.d.ts
types/User/UserCreateParameters.d.ts
types/demo/README.md
types/demo/index.ts
types/demo/package-lock.json
types/demo/package.json

Adds the following missing un-implemented Typescript definitions:
- CustomsInfo
- CustomsItem
- ScanForm
- User
- Referral
- Rate
- CarbonOffset
- Brand
Closes #328 

fix typescript

---

CHANGELOG.md
src/resources/event.js
src/resources/payload.js
src/resources/user.js
test/cassettes/Event-Resource_1173491181/retrieves-a-payload-for-an-event_1410906611/recording.har
test/cassettes/Event-Resource_1173491181/retrieves-all-events_1562474214/recording.har
test/cassettes/Event-Resource_1173491181/retrieves-all-payloads-for-an-event_3292460230/recording.har
test/cassettes/Event-Resource_1173491181/retrieves-an-event_1451703989/recording.har
test/resources/event.test.js
types/Payload/Payload.d.ts
types/Payload/index.d.ts

- New static functions to retrieve payload(s) for an event
- New Payload model and TypeScript definition
- New unit tests, cassettes to test payload functions
- New recordings for other event unit tests (oops)
- Improvements to docstrings
Since a Payload object does not have any instance functions (and as a small POC of the upcoming redesign), the Payload class does not extend the base class. As a result, there are a handful of functions (e.g. construction from JSON) that had to be ported out of the base class and re-implemented in the Payload class. It was either that, or extend the base class and override the various instance functions (`save`, `delete`, `all`) to not be implemented. In my opinion, this is a cleaner, safer approach.
The JSON of the response to retrieving all payloads …

feat: Add functions to retrieve event payload(s)

---

CHANGELOG.md
package.json

chore: prepare v5.10.0 for release

---

types/Pickup/Pickup.d.ts
types/Pickup/PickupListParameters.d.ts

Adds missing definition for `Pickup.all()` function.
- N/A

[fix] Add TypeScript definition for Pickup all function

---

README.md

docs: adds library documentation link to README

---

CHANGELOG.md
docs/billing.js.html
docs/referral.js.html
src/beta/resources/referral.js
src/resources/billing.js
src/resources/referral.js
types/Billing/Billing.d.ts
types/Referral/Referral.d.ts

Because we are about to release a major version of this lib, we can rename the `primaryOrSecondary` param without issue and call it out in the CHANGELOG.
NA

fix: priority param name

---

CHANGELOG.md
src/resources/base.js
src/resources/billing.js
src/resources/tracker.js
test/resources/billing.test.js
test/resources/carrier_account.test.js
test/resources/tracker.test.js
test/resources/user.test.js
test/resources/webhook.test.js
types/Billing/Billing.d.ts
types/Carrier/CarrierAccount/CarrierAccount.d.ts
types/Webhook/Webhook.d.ts

As with other thread-safe rewrites, we are making all functions that have an empty response return `void` to better match the API. This PR makes those changes.
Tests were updated to assert that no errors are thrown.

fix: empty responses now return void

---

test/cassettes/Refund-Resource_710135213/creates-a-refund_2084766157/recording.har
test/resources/refund.test.js

Sends tracking codes as a list instead of a string

fix: refund test

---

.npmignore
CHANGELOG.md
package.json

Overhauls the previous npmignore which was much too lenient and instead explicitly tell it what should make it to the final package.
Closes #343 
```
jhammond@easypost-node $ npm pack --dry-run
npm notice 
npm notice 📦  @easypost/api@5.10.1
npm notice === Tarball Contents === 
npm notice 1.1kB   LICENSE                                                         
npm notice 2.1kB   src/resources/address.js                                        
npm notice 1.2kB   src/resources/api_key.js                                        
npm notice 319B    src/resources/base_address.js                                   
npm notice 8.2kB   src/resources/base.js                                           
npm notice 2.8kB   src/resources/batch.js                                          
npm notice 257B …
```

fix: npmignore list to properly package library

---

src/beta/beta_referral_customer_service.js
src/beta/easypost.js
src/easypost.js
src/services/address_service.js
src/services/api_key_service.js
src/services/base_service.js
src/services/batch_service.js
src/services/billing_service.js
src/services/carrier_account_service.js
src/services/carrier_type_service.js
src/services/customs_info_service.js
src/services/customs_item_service.js
src/services/end_shipper_service.js
src/services/event_service.js
src/services/insurance_service.js
src/services/order_service.js
src/services/parcel_service.js
src/services/pickup_service.js
src/services/rate_service.js
src/services/referral_customer_service.js
src/services/refund_service.js
src/services/report_service.js
src/services/scan_form_service.js
src/services/shipment_service.js
src/services/tracker_service.js
src/services/user_service.js
src/services/webhook_service.js

make functions and fields private/protected
Unit tests passed

make functions and fields private/protected if needed

---

src/services/billing_service.js
src/utils/util.js

This PR modernizes a few syntax issues found by looking through this list as a good example to follow: https://github.com/orgs/mdn/discussions/143
Amazingly, either these were already done, aren't possible with our styleguide, or aren't possible with our supported Node versions

chore: modernize syntax

---

CHANGELOG.md
src/beta/beta_rate_service.js
src/beta/easypost.js
src/easypost.js
src/utils/util.js
test/cassettes/Beta-Rate-Service_115363300/retrieve-invalid-lowest-rate_1308734214/recording.har
test/cassettes/Beta-Rate-Service_115363300/retrieve-the-lowest-rate_1860369698/recording.har
test/cassettes/Beta-Rate-Service_115363300/retrieves-a-list-of-stateless-rates_708839575/recording.har
test/services/beta/beta_rate.test.js
test/services/shipment.test.js

- Add `retrieveStatelessRates` and `getLowestStatelessRate` functions
add unit tests

feat(beta): Add stateless rating

---

CHANGELOG.md
UPGRADE_GUIDE.md

Adds the v6 upgrade guide in preperation for the v6 release

docs: write v6 upgrade guide

---

CHANGELOG.md
Makefile
package-lock.json
package.json

chore: prepare v6.0.0-rc1 for release

---

.gitignore
CHANGELOG.md
package-lock.json
package.json

chore: prepare v6.0.0 for release

---

CHANGELOG.md
package-lock.json
package.json

chore: prepare v6.1.0 for release

---

CHANGELOG.md
src/models/user.js

Adds the missing `api_keys` property to `User`, closes #366

fix: add missing api_keys to User

---

.github/workflows/ci.yml

chore: test against Node 20

---

CHANGELOG.md
package-lock.json
package.json
types/Carrier/CarrierMetadata/CarrierMetadata.d.ts
types/Carrier/CarrierMetadata/index.d.ts
types/Carrier/index.d.ts

- Adds `CarrierMetadata` typescript definitions
- Prepares v6.3.0 for release

feat: carrier metadata typescript definitions

---

CHANGELOG.md
package-lock.json
package.json

chore: prepare v6.4.0 for release

---

CHANGELOG.md
types/EasyPost.d.ts
types/Utility/Utils.d.ts
types/Utility/index.d.ts
types/index.d.ts

Adds missing typescript definitions for `Utility` class

Adds missing typescript definitions for Utility class

---

CHANGELOG.md
src/constants.js
src/easypost.js
src/models/order.js
src/models/pickup.js
src/models/shipment.js
src/services/shipment_service.js
src/utils/util.js
test/services/beta_rate.test.js
test/services/shipment.test.js
test/services/webhook.test.js

We never exposed `Utils` correctly to the end users. This PR moves utils to EasyPostClient

Move utils to EasyPostClient

---

CHANGELOG.md
package-lock.json
package.json

chore: prepare v6.5.0 for release

---

CHANGELOG.md
README.md
package-lock.json
package.json

Bumps deps and adds support for Typescript 5

chore: bump deps and add support for Typescript 5

---

CHANGELOG.md
README.md
src/errors/api/bad_request_error.js
src/errors/error_handler.js

Maps 400 status codes to new `BadRequestError` class

feat: map 400 status codes to BadRequestError class

---

CHANGELOG.md
package.json

chore: prepare v6.7.0 for release

---

src/utils/util.js

Checks for a lowercased hmac signature header.
Closes #399.

Check for lowercased signature header

---

CHANGELOG.md
package-lock.json
package.json

chore: prepare v6.7.1 for release

---

CHANGELOG.md
package-lock.json
package.json

[chore] Prep release

---

test/cassettes/ReferralCustomer-Service_3380152635/add-a-referral-user-credit-card_1978527022/recording.har
test/cassettes/ReferralCustomer-Service_3380152635/creates-a-referral-user_159009729/recording.har
test/cassettes/ReferralCustomer-Service_3380152635/retrieves-all-referral-users_447651186/recording.har
test/cassettes/ReferralCustomer-Service_3380152635/retrieves-next-page-of-referral-customer_33395404/recording.har
test/cassettes/ReferralCustomer-Service_3380152635/updates-a-referral-user_2206325082/recording.har
test/services/referral_customer.test.js

Cassettes for referral customer unit tests in #406 were incorrect and have been re-recorded

[chore] Fix referral customer cassettes

---

CHANGELOG.md
src/services/user_service.js
test/cassettes/User-Service_2658581389/retrieves-parent-user-s-API-keys_3733038849/recording.har
test/cassettes/User-Service_2658581389/throws-FilteringError-when-trying-to-retrieve-child-user-s-API-keys_933533041/recording.har
test/services/user.test.js

Add missing method to get API keys that was not present in our Node client.
Added unit tests and recorded appropriate cassettes for the involved HTTP interactions.

Add apiKeys method to User service

---

CHANGELOG.md
package-lock.json
package.json

chore: prepare v6.8.0 for release

---

src/services/scan_form_service.js
test/cassettes/ScanForm-Service_1241997233/creates-a-scanform_355573720/recording.har
test/cassettes/ScanForm-Service_1241997233/retrieves-a-scanform_3128791796/recording.har
test/cassettes/ScanForm-Service_1241997233/retrieves-all-scanforms_428090277/recording.har
test/cassettes/ScanForm-Service_1241997233/retrieves-next-page-of-scanforms_2978606387/recording.har
test/services/scan_form.test.js

Payload parameter generation for "create scan form" function was using a non-existent variable, causing a malformed payload and failing any scan form creation API call.
- Re-record all scan form unit tests to verify patch is effective

[bug] Fix bad payload construction for creating scan forms

---

CHANGELOG.md
package-lock.json
package.json

Bump version number, update CHANGELOG
- N/A

[chore] Prep for v6.8.1 release

---

CHANGELOG.md
package-lock.json
package.json

[chore] Prep for v6.8.2 release

---

src/services/base_service.js
test/services/base_service.test.js

- Fixes pagination bug (See [Python library](https://github.com/EasyPost/easypost-python/pull/303) for details)
- Add unit test to verify pagination workflow retrieves all valid pages

[fix] Remove bad guard clause on pagination handling

---

CHANGELOG.md
src/services/user_service.js
test/cassettes/User-Service_2658581389/retrieves-a-paginated-list-of-children_3912335410/recording.har
test/cassettes/User-Service_2658581389/retrieves-next-page-of-children_3033480518/recording.har
test/services/user.test.js
types/User/User.d.ts

- Adds `allChildren` function in User service to get a paginated list of children
- Adds `getNextPage` function in User service to get next paginated list of children
Add new unit tests

add allChildren and getNextPage functions

---

CHANGELOG.md
package-lock.json
package.json

- Bump version number
- Update changelog

[chore] Prep for v7.1.0 release

---

CHANGELOG.md
package-lock.json
package.json

chore: prepare v7.2.0 for release

---

CHANGELOG.md
package-lock.json
package.json
src/services/billing_service.js
test/services/billing.test.js

prep release v7.3.0

---

CHANGELOG.md
package-lock.json
package.json

chore: prepare v7.3.1 for release

---

CHANGELOG.md
package-lock.json
package.json

Update changelog, bump version number

[chore] Prep for v7.4.0 release

---

CHANGELOG.md
package-lock.json
package.json
src/services/claim_service.js
types/Claim/Claim.d.ts

prep release v7.5.0

---

CHANGELOG.md
src/models/rate.js

feat: adds missing properties to Rate model

---

CHANGELOG.md
src/services/user_service.js
test/cassettes/User-Service_2658581389/retrieves-next-page-of-children_3033480518/recording.har

Fix getNextPage in User Service where it should use `after_id` key
re-record cassette

Fix getNextPage in User Service

---

CHANGELOG.md
package-lock.json
package.json
src/services/user_service.js

prep release v7.5.1

---

.github/workflows/release.yml

fix: install before publishing

---

CHANGELOG.md
package-lock.json
package.json

chore: prep v7.5.2 for release

---

CHANGELOG.md
package-lock.json
package.json

Bump version number, update changelog

[chore] Prep for v7.5.3 release

---

vitest.config.js

After switching to Vitetest, the code coverage report generation was altered. This change now generates the HTML for humans along with lcov needed for coveralls
Ran `make coverage` and inspected the `lcov.info` file was output

fix: coverage report generation

---

CHANGELOG.md
package-lock.json
package.json

chore: prep v7.5.5 for release

---

CHANGELOG.md
package-lock.json
package.json

chore: prep v8.0.1 for release
