EasyPost/easypost-node

- lib/main.js
- test/main.js
This commit adds an optional timeout param into the easypost library.
This gives users the ability to specify what timeout value they would
like to use when making requests to the Easypost API.
If a timeout is not passed in, a default timeout of 120000ms is used.
> Add timeout option

- src/easypost.js
- src/resources/scan_form.js
- test/resources/scan_form.js
@ajacksified object creation doesn't match the objects that are returned.
curl:
`curl -X POST https://api.easypost.com/api/v2/scan_forms -u <api_key>: -d '{"shipments":[{"id":"shp_59515f02dfb84fbe972c94f69bbb2aec"}]}' -H 'Content-Type: application/json'`
Few questions:
Do I need `jsonIdKeys`? What is that field for?
Should I be overriding `toJSON` so that `new api.ScanForm({shipments: [{id: "shp_59515f02dfb84fbe972c94f69bbb2aec"}]})` works?
> /scan_forms endpoint (api.ScanForm)

- package.json
- src/resources/carrierAccount.js
- src/resources/tracker.js
- src/resources/user.js
Can't seem to find any docs/usage of `T.any()` https://facebook.github.io/react/docs/typechecking-with-proptypes.html. 
I came across this error when trying to create a Tracker:
const tracker = new api.Tracker({tracking_code: '9405510200793925708347'})
tracker.save().then(console.log)
{
name: 'ValidationError',
errors:
{ tracking_details: 'Error: Invalid prop `tracking_details` of type `array` supplied to `Tracker`, expected `object`.',
created_at: 'Error: Invalid prop `created_at` of type `string` supplied to `Tracker`, expected `object`.',
updated_at: 'Error: Invalid prop `updated_at` of type `string` supplied to `Tracker`, expected `object`.' },
status: 422 }
at https://github.com/EasyPost/easypost-node/blob/master/src/resources/base.js#L77
console.log(key) // 'created_at' …
> proptype T.any should be T.oneOfType

- src/resources/base.js
- src/resources/parcel.js
- test/resources/base.js
- test/resources/parcel.js
@k-funk  Do you know why the wrapping key was removed here? https://github.com/EasyPost/easypost-node/commit/cb71fe15dd020a1b1b3b7a884b9eb7c7c6383864#diff-83a975aa8cf501970485ca625ed9df32R22
This fixes an open ticket about parcel creation.
> Wrap parcel json

- package.json
- src/resources/report.js
waiting on backend changes from @victoryftw to make this work (currently 404's because of a routing issue)
> retrieve reports by id without needing to pass the type

- src/resources/customsItem.js
- test/resources/customsItem.js
CustomsItem.value is a string in order to represent decimal values;
JSON and javascript only use low precision floats, so treat the value of
`value` like a string, as it comes in over the api.
For #76
> CustomsItem.value is a string

- package.json
New dep that isn't installed without dev-dependencies, for
async-to-generator transforms.
For #89
> Add nodent-runtime dependency

- src/resources/base.js
- test/resources/address.js
- test/resources/apiKey.js
- test/resources/base.js
- test/resources/batch.js
- test/resources/carrierAccount.js
- test/resources/carrierType.js
- test/resources/customsInfo.js
- test/resources/customsItem.js
- test/resources/insurance.js
- test/resources/order.js
- test/resources/parcel.js
- test/resources/pickup.js
- test/resources/report.js
- test/resources/scan_form.js
- test/resources/shipment.js
- test/resources/tracker.js
- test/resources/user.js
- test/resources/webhook.js
Allow deleting a model instace that has an id as an alternative to ModelClass.delete(id).
Closes issue #90
> instance.delete()

- README.md
The README could use some spring cleaning. Many of the commands were bunched together in an unreadable way or there was better formatting available. Additionally, none of the code blocks had formatting set which I added. Lastly, I added development and releasing information as they were notably missing to this point.
This change brings the Node client library README in line with how many of the other client library README's are laid out.
> Cleaned Up README, Fixed Typos, and Added Development Info

- src/resources/apiKey.js
- test/resources/apiKey.js
Our other client libraries such as PHP, Python, and Ruby allow for individual user API key retrieval. Our docs say that you can retrieve them but only return `undefined` (separate issue opened to update docs):
**Bad Example:**
```node
const Easypost = require('@easypost/api');
const api = new Easypost('<YOUR_TEST/PRODUCTION_API_KEY>');
// Load child keys
api.User.retrieve('user_...')
.then(child => console.log(child.api_keys));
```
Without the ability to just retrieve a single key (say a child key you don't have on file) to update something, you currently have to engineer some really weird workarounds like one we've used with a customer where they knew the name/id of the user but needed the individual key and couldn't get it unless they were all retrieved, matched, and filtered (don't …
> Allow API Key retrieval

- src/resources/address.js
- test/resources/address.js
The Node client library does not allow users to retrieve all `addresses` but the other CL's do. I've removed the `NotImplemented` code to allow users to retrieve all records as 1) the API supports this functionality and 2) the other CL's allow for these methods on these objects.
> Allows all records for addresses

- src/resources/shipment.js
- test/resources/shipment.js
Shipments cannot be returned simply by calling the ID. Documentation has already been corrected but the client library needs this item removed as well. The documentation example (which has since been removed) looked like this:
```javascript
// Alternatively, return an instance you've already loaded.
api.Shipment.retrieve('shp_...').then(s => {
s.return().then(() => console.log(s));
});
```
As this isn't supported and the documentation has been corrected, this should also be removed from the client library.
There was conversation around whether to just release this (breaking change), or wait for another fix and sneak it in together.
> Removed shipment return

- src/resources/order.js
- test/resources/order.js
The orders endpoint is not paginated for all orders and as such, should be removed due to low usage and performance.
> Remove Orders.all method

- src/resources/shipment.js
We've changed the `usps_zone` field on the API side from a `string` to an `integer` and need to update the `propType` here to match.
Closes #169
> fix: changes usps_zone from string to integer

- package.json
Pins `@easypost/build` to 2.6.4 to fix a regression introduced by bumping `mini-css-extract-plugin` in 2.6.6
> pin to @easypost/build == 2.6.4 to fix a regression introduced by bumping mini-css-extract-plugin

- CHANGELOG.md
- package.json
Version bump so we can rebuild the assets that weren't published in v3.11.0
Closes #175
> Bump version to 3.11.1 so we can repackage and republish

- src/resources/shipment.js
Apparently the `propType` of an `integer` is supposed to be a `number` here: https://www.npmjs.com/package/prop-types
Fixes the `usps_zone` field type.
> fix: changes usps_zone from integer to number type

- CHANGELOG.md
- package.json
Version bump:
* Corrects the `usps_zone` propType from integer to number
> chore: version bump to 3.11.2

- src/resources/shipment.js
This PR adds support for the new `tax_identifiers` object.
End-to-end tested this (requires https://github.com/EasyPost/easypost-node/pull/186), and got it working: 
```javascript
tax_identifiers: [
{
entity: 'SENDER',
tax_id: '12345',
tax_id_type: 'EORI',
issuing_country: 'GB'
}
],
```
> feat: adds support for tax_identifiers

- CHANGELOG.md
- src/easypost.js
Currently, connections would stay open for up to 120 seconds which is far too long for an API context.
60 seconds was chosen as it's long enough not to be hostile but short enough to not leave connections open for vast amounts of time. We are standardizing timeouts across all the libraries.
> chore: lowered the default timeout of requests from 120 seconds to 60

- .github/workflows/ci.yml
- package.json
We have a `lint` npm target but don't use it on CI. Let's do so to enforce our style on PRs.
> chore: run linting on CI

- CHANGELOG.md
- src/easypost.js
Adds the Node version to the user-agent header.
Tested via the repl:
```bash
jhammond@easypost-node $ node
Welcome to Node.js v14.18.2.
Type ".help" for more information.
> process.versions.node
'14.18.2'
```
> feat: adds the Node version to the user-agent header

- CHANGELOG.md
- src/resources/order.js
Adds support to one-call buy an order by adding the missing `service` field to the order object. You one-call buy an order just as you would a shipment, by passing the `service` you want to purchase and the `carrier_account` ID of the carrier it belongs to.
This was end-to-end tested to ensure it works properly.
> feat: add support to one-call buy an order

- CHANGELOG.md
- src/resources/shipment.js
- test/resources/shipment.js
This PR removes **retrieveRate()** in the shipment class and its belonging unit tests because the shipment object already has rates, which makes this method unnecessary. If you need to get new rates for a shipment, please use **regenerateRate()** method.
> remove retrieveRate() method and its unit tests.

- CHANGELOG.md
- src/resources/user.js
- test/resources/user.js
Node library is currently missing the **`retrieve_me`** function. This is the same as retrieving a user without specifying an ID, but some libs have a specific function for this. Unifying this to make our libraries more consistent.
> Retrieve me

- .babelrc
- .github/workflows/ci.yml
- .gitignore
- CHANGELOG.md
- README.md
- package.json
- webpack.config.babel.js
Drops support for Node < 10 and removes the build matrix for those versions.
> chore: drops support for Node < 10

- CHANGELOG.md
- src/resources/apiKey.js
- test/resources/apiKey.js
This PR removes enable() and disable() API Key functionality and unit tests as well. Users should not have the ability to enable/disable via API call, they should use this feature through the EasyPost website.
> remove enable/disable apikey functionality.

- .babelrc
- CHANGELOG.md
- package-lock.json
- package.json
- webpack.config.babel.js
Replaces `@easypost/build` with a standalone Webpack config. Builds the same as it previously did with the one exception of not containing the various `_temp` vars throughout that were copies of the `_class` vars.
I was able to build the wepback successfully and then run tests against the new built file successfully (real API calls)
> chore: Use Standalone Webpack Instead of @easypost/build

- src/resources/base.js
- test/cassettes/Address-Resource_3542783961/retrieves-all-addresses_2336737309/recording.har
- test/resources/address.js
- test/resources/base.js
It appears the Node library is unwrapping the responses from the `all` methods to create something like the following:
```
{
[
Shipment {
_validationErrors: null,
created_at: '2021-12-08T15:53:32Z',
is_return: false,
...
},
has_more: true
]
}
```
When all our other client libraries and documentation do not unwrap the responses:
```
{
"shipments": [
{
"batch_id": null,
"batch_message": null,
"batch_status": null,
...
}
],
has_more: true
}
```
This PR stops unwrapping responses from the `all` endpoint so the key of the objects in question will exist (matching our docs and other client libraries) and the `has_more` key will be populated properly where it's supposed to be.
**This is a breaking change and will require a major version bump.**
There are probably better ways to correct this …
> fix: do not unwrap "all" endpoint responses

- CHANGELOG.md
- src/resources/customs_item.js
Corrects the `customs_item.value` propType from string to number. This should have always been number, because the Javascript spec defines a number as a whole number or a decimal. Our docs have this field as a float so this now more clearly defines what is acceptable in this field:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number
> fix: customs_item.value propType

- src/easypost.js
- src/errors/error.js
- src/resources/address.js
- src/resources/api_key.js
- src/resources/base.js
- src/resources/batch.js
- src/resources/brand.js
- src/resources/carrier_type.js
- src/resources/customs_info.js
- src/resources/customs_item.js
- src/resources/event.js
- src/resources/insurance.js
- src/resources/order.js
- src/resources/parcel.js
- src/resources/pickup.js
- src/resources/rate.js
- src/resources/report.js
- src/resources/scan_form.js
- src/resources/shipment.js
- src/resources/tracker.js
- src/resources/user.js
- test/resources/customs_item.js
- Adds `jsdoc` style blocks to each function (I tried keeping things generic for now, we can tighten these down as time goes on)
- Moves `constructors` to be the first thing in their respective classes
- Adds `brand` ID which was previously missing to ensure proper documentation
- Removes custom `save` function from customs_item class that was missed in the previous PR
> chore: adds jsdoc style blocks to each function

- src/resources/report.js
- test/cassettes/Report-Resource_72515537/creates-a-report-by-specifying-columns_1660528128/recording.har
- test/cassettes/Report-Resource_72515537/creates-a-report-with-additional-columns_3168456315/recording.har
This PR moves the columns and additional_columns from URL query to request body because a long query URL can be rejected or silently truncated. Basically, the overridden `save()` is removed and then re-record cassettes.
E2E test:
> move columns and additional_columns from url query to request body.

- CHANGELOG.md
- src/easypost.js
- src/resources/refund.js
- test/cassettes/Refund-Resource_710135213/creates-a-refund_2084766157/recording.har
- test/cassettes/Refund-Resource_710135213/retrieves-a-refund_348903105/recording.har
- test/cassettes/Refund-Resource_710135213/retrieves-all-refunds_2266923862/recording.har
- test/resources/refund.test.js
Our API allows you to either refund a shipment from the `shipment` object or from the `Refund` class; however, the `refund` class is currently missing from the Node library.
This PR adds the missing `Refund` class and unit tests to make sure they are working as expected.
> add refund class.

- src/easypost.js
- src/resources/address.js
- src/resources/base.js
- src/resources/batch.js
- src/resources/carrier_account.js
- src/resources/carrier_type.js
- src/resources/refund.js
- src/resources/tracker.js
- src/resources/user.js
- test/cassettes/Batch-Resource_4123662849/buys-a-batch_1852613799/recording.har
- test/cassettes/Batch-Resource_4123662849/creates-a-scanform-for-a-batch_397052124/recording.har
- test/cassettes/Batch-Resource_4123662849/generates-a-label-for-a-batch_2376202846/recording.har
- test/cassettes/Pickup-Resource_1673862587/buys-a-pickup_1934475561/recording.har
- test/cassettes/Pickup-Resource_1673862587/cancels-a-pickup_4207662041/recording.har
- test/cassettes/Pickup-Resource_1673862587/creates-a-pickup_320342919/recording.har
- test/cassettes/Pickup-Resource_1673862587/retrieves-a-pickup_3320623723/recording.har
- test/cassettes/Shipment-Resource_2534528937/refunds-a-shipment_2011747091/recording.har
- test/cassettes/Shipment-Resource_2534528937/regenerates-rates-for-a-shipment_3874762135/recording.har
- test/helpers/fixture.js
Similar to our [change on the C# library](https://github.com/EasyPost/easypost-csharp/pull/257), this PR removes the developer's ability to indicate where parameters are placed, and instead handles that logic internally to prevent possible user/developer error.
- Let the EasyPost client decide where to put parameters (query or body), rather than developer doing so.
Re-ran cassettes
> Handle parameter placement internally

- CHANGELOG.md
- package-lock.json
- src/beta/easypost.js
- src/beta/resources/end_shipper.js
- src/resources/address.js
- src/resources/base_address.js
- test/cassettes/Address-Resource_3542783961/creates-an-address-with-verify-param_348500273/recording.har
- test/cassettes/Address-Resource_3542783961/creates-an-address_3623959033/recording.har
- test/cassettes/Address-Resource_3542783961/verifies-an-address_2951018147/recording.har
- test/cassettes/EndShipper-Resource_10951045/creates-an-EndShipper-object_2102997832/recording.har
- test/cassettes/EndShipper-Resource_10951045/retrieves-all-EndShipper-objects_92306777/recording.har
- test/cassettes/EndShipper-Resource_10951045/retrieves-all-EndShippers_2062946142/recording.har
- test/cassettes/EndShipper-Resource_10951045/retrieves-an-EndShipper-object_1126490324/recording.har
- test/cassettes/EndShipper-Resource_10951045/retrieves-an-EndShipper_3983980685/recording.har
- test/cassettes/EndShipper-Resource_10951045/updates-an-EndShipper-object_792713925/recording.har
- test/cassettes/EndShipper-Resource_10951045/updates-an-EndShipper_2134048290/recording.har
- test/cassettes/Shipment-Resource_2534528937/creates-a-shipment-when-only-IDs-are-used_3469201880/recording.har
- test/helpers/fixture.js
- test/resources/beta/end_shipper.test.js
Adds the new EndShipper beta class with retrieve, all, and save functions. This is the fully-qualified address object that the USPS will start requiring shortly.
Add `BaseAddress` propTypes that `Address` and `EndShipper` can use
Add unit tests
> Add EndShipper beta class.

- .github/workflows/ci.yml
Force `npm install` for now to unblock builds (have been doing this locally for the better part of half a year now) but CI is now catching on and is unhappy.
The only way around this is to drop support for Node 10 and further modernize our dependencies in use.
> fix: build install step

- .github/workflows/ci.yml
- package-lock.json
- package.json
Adds `audit-ci` as a security analysis dependency tool. 
We currently only have it fail on critical security vulnerabilities as there are known high and medium vulnerabilities in this library. Unfortunately, without bumping to at least Node 12 we can't remediate that fact. When we release our next major version of this lib, we'll bump the minimum Node version to at least Node 12 which will allow us to bump dependencies and fix these vulnerabilities.
> feat: reintroduces audit-ci to project

- .gitattributes
Properly ignores cassettes since they are actually nested in sub folder.
> fix: gitattributes to ignore cassettes

- README.md
Removes a TODO from the README for Typescript as it was added when we released Typescript.
> docs: remove report Typescript TODO from README

- CHANGELOG.md
- src/resources/billing.js
- types/Billing/Billing.d.ts
- types/Billing/index.d.ts
- types/PaymentMethod/PaymentMethod.d.ts
- types/PaymentMethod/index.d.ts
Add typescript definition for Billing and PaymentMethod
Correct return type for Billing functions(`deletePaymentMethod`, `fundWallet`)
N/A
> add typescript definition for Billing and PaymentMethod and correct return type for Billing functions

- .gitattributes
Finally fixed the gitattributes for ignoring cassette diffs. This doesn't work as nicely for this lib because Polly stores them two directories deep. We can safely ignore `.har` files because those are the cassettes and nothing else.
> fix: ignore cassettes via gitattributes for real

- CHANGELOG.md
- src/resources/webhook.js
- test/helpers/fixture.js
- test/resources/webhook.test.js
- types/Webhook/Webhook.d.ts
Adds a new `validateWebhook` function which takes in an `event_body` and `headers` from an EasyPost webhook and your locally stored `webhook_secret` and ensures the webhook originated from EasyPost. Will raise an error if the secrets don't match and produce your webhook if they do.
Adds 3 unit tests to ensure all branches of this function work as intended.
> feat: adds validateWebhook function

- CHANGELOG.md
- src/resources/address.js
- test/cassettes/Address-Resource_3542783961/creates-an-address-with-an-array-verify-param_1154761701/recording.har
- test/cassettes/Address-Resource_3542783961/creates-an-address-with-verify-param_348500273/recording.har
- test/resources/address.test.js
- types/Address/AddressCreateParameters.ts
Allows for looser values to the `verify` and `verify_strict` params when creating an address (can accept strings or bools outside of an array)
- Updates old unit tests to use a bool
- Adds a new unit test to ensure arrays still work
> chore: looser params for verify and verify_strict

- test/resources/address.test.js
- test/resources/api_key.test.js
- test/resources/batch.test.js
- test/resources/beta/referral.test.js
- test/resources/billing.test.js
- test/resources/event.test.js
- test/resources/insurance.test.js
- test/resources/order.test.js
- test/resources/pickup.test.js
- test/resources/refund.test.js
- test/resources/report.test.js
- test/resources/scan_form.test.js
- test/resources/shipment.test.js
- test/resources/tracker.test.js
- test/resources/webhook.test.js
We want to be asserting that items are present. In Javascript, we should be using `undefined` instead of `null` to do this. We found we got burned by using `null` on a few items that provided false-positives. These were corrected:
1. Carbon offset not getting set properly (fixed in a previous PR that spurred these fixes here)
2. API keys are being massaged into a differing format than what we have documented (TODO left for the future as to not break the behavior here)
3. Webhooks are unpaginated and do not have a `has_more` key, assertion removed
4. Fixes a couple spots where we weren't using the proper `mocha` assertion syntax
- All tests that test against `null` were changed to `undefined` for presence checks
> fix: assert that items are undefined instead of null

- package-lock.json
- package.json
- src/beta/easypost.js
- src/easypost.js
- src/resources/end_shipper.js
- test/cassettes/EndShipper-Resource_10951045/creates-an-EndShipper-object_2102997832/recording.har
- test/cassettes/EndShipper-Resource_10951045/retrieves-all-EndShipper-objects_92306777/recording.har
- test/cassettes/EndShipper-Resource_10951045/retrieves-an-EndShipper-object_1126490324/recording.har
- test/cassettes/EndShipper-Resource_10951045/updates-an-EndShipper-object_792713925/recording.har
- test/resources/end_shipper.test.js
- Moved EndShipper from beta to main namespace
- We can't have two classes with the same name/path (EndShipper was always `easypost.EndShipper`, not `easypost.beta.EndShipper`), so the beta class has been deleted
- Update unit tests
- Unit tests updated and passing
> Move EndShipper to general availability

- CHANGELOG.md
- package-lock.json
- src/beta/resources/referral.js
- src/easypost.js
- src/errors/request.js
- test/errors/request.js
Fixes a regression introduced in v5.1.0 that included the entire response instead of the response body when errors are returned from the API. We will continue to fallback to the entire response when a body isn't present. 
This also switches the `RequestError` to `Error` for the referral function when we cannot connect to Stripe since that was the wrong error type and would blow up at runtime due to the message being passed in not being a response object. This wasn't caught because we don't run this unit test.
A/B tested the output of an error with/without the fix.
Without the fix:
```bash
...
},
created: false,
accepted: false,
noContent: false,
badRequest: false,
unauthorized: false,
notAcceptable: false,
forbidden: false,
notFound: false,
unprocessableEntity: true,
type: …
```
> fix: only include the response body for errors instead of the entire response

- src/errors/request.js
- test/cassettes/Error-Resource_153777519/pulls-out-error-properties-of-an-API-error_2733221812/recording.har
- test/helpers/common.js
- test/resources/error.test.js
Adds an error test to ensure the error object can have properties pulled out of it. 
This lib deviates wildly from what our API docs state and the expectations of the Error object that we can't yet concatenate the error message without doing a bunch of other work. I left a bunch of TODOs for now and will revisit fixing error handling when we do the thread-safe rewrite
Adds a new test to check that unpacking error properties works
> tests: adds error test

- CHANGELOG.md
- README.md
- src/beta/easypost.js
- src/beta/resources/beta_payment_refund.js
- src/beta/resources/referral.js
- test/cassettes/Referral-Beta-Resource_682743806/Refund-a-payment-by-a-payment-log-ID_834598297/recording.har
- test/cassettes/Referral-Beta-Resource_682743806/Refund-by-amount-for-a-recent-payment_2095459785/recording.har
- test/cassettes/Referral-Beta-Resource_682743806/add-payment-method-to-a-referral-customer-account_202490475/recording.har
- test/resources/beta/referral.test.js
- test/resources/referral.test.js
- types/Referral/Referral.d.ts
- types/Referral/index.d.ts
- [ADDED] Adds new beta billing functionality for ReferralCustomer users
- `addPaymentMethod` can add a pre-existing Stripe bank account or credit card to your EasyPost account
- `refundByAmount` refunds your wallet by a dollar amount
- `refundByPaymentLog` refunds you wallet by a PaymentLog ID
Add unit tests
> add stripe refund and add payment functionalities

- .npmignore
Ports the npmignore file changes from v5 to master after confirming they worked to greatly reduce the size of our final package while including what was needed.
> fix: ports the npmignore from v5 to master

- .eslintrc
- package.json
- test/.eslintrc
- test/helpers/common.js
Removed `@easypost/eslint-config-easypost-base` as it's no longer maintained and is about to get deprecated, replaced the style guide with `eslint:recommended` and set up some basic config.
> update style guide to use eslint:recommended

- types/Webhook/Webhook.d.ts
remove `validateWebhook` in the typescript file because it no longer belongs to `webhook` class
Closes #377 
> remove validateWebhook in the typescript file

- types/Pickup/PickupCreateParameters.d.ts
closes #390 
Instead of importing the `PickupRate` class from the Javascript library, I imported the `IPickupRate` interface from the local `PickupRate.d.ts` declaration files. This fixes the compilation issues described in #390.
TypeScript using this package compiles correctly. Like the rest of the types code, this can't be tested.
> import correct `PickupRate` type

- types/EasyPost.d.ts
CarrierMetadata is missing from the EasyPost class, this fixes this minor bug.
This fixes a typescript error when attempting to use easyPostClient.CarrierMetadata
Bug fix (non-breaking change which fixes an issue)
> Add CarrierMetadata to EasyPost typescript definition

- CHANGELOG.md
- src/constants.js
- FedEx SmartPost carrier account registration should hit `/register` endpoint for creation
> [fix] FedEx SmartPost hits register endpoint

- src/services/user_service.js
There was an error in the docstring for `apiKeys` that prevents docs generation to happen. This fixes it.
`make docs` now succeeds
> Fix docstring for apiKeys method

- CHANGELOG.md
- package-lock.json
Fixes https://github.com/EasyPost/easypost-node/security/dependabot/52
> chore: bump dependencies to fix vulnerability

- CHANGELOG.md
- UPGRADE_GUIDE.md
- package-lock.json
- package.json
Prep v7 major release with upgrade guide
> Prep v7 major release

- types/Address/Address.d.ts
- types/Event/Event.d.ts
- types/Insurance/Insurance.d.ts
- types/Pickup/Pickup.d.ts
- types/Referral/Referral.d.ts
- types/Refund/Refund.d.ts
- types/Report/Report.d.ts
- types/ScanForm/ScanForm.d.ts
- types/Shipment/Shipment.d.ts
- types/Tracker/Tracker.d.ts
- types/User/User.d.ts
- Adds TypeScript definitions for all `getNextPage` functions
Waiting for #427 
N/A
> [chore] Add TS docstring for getNextPage functions

- .github/workflows/ci.yml
- package.json
- test/cassettes/Address-Service_1115845720/creates-a-verified-address_2691107999/recording.har
- test/cassettes/Address-Service_1115845720/creates-an-address-with-an-array-verify-param_1154761701/recording.har
- test/cassettes/Address-Service_1115845720/creates-an-address-with-verify-param_348500273/recording.har
- test/cassettes/Address-Service_1115845720/creates-an-address-with-verify_strict-param_3337987013/recording.har
- test/cassettes/Address-Service_1115845720/throws-an-error-when-we-cannot-create-and-verify-an-address_2925377245/recording.har
- test/cassettes/Address-Service_1115845720/throws-an-error-when-we-cannot-verify-an-address_2852976208/recording.har
- test/cassettes/Address-Service_1115845720/verifies-an-address_2951018147/recording.har
- test/services/address.test.js
See https://github.com/EasyPost/easypost-csharp/pull/540 for more details.
- Update examples submodule for new "incorrect address" fixture
- Update address verification unit tests to better test target functionality
- Update unit tests, re-record cassettes as needed
- Update CI to match other libraries (run unit tests in all Node versions, run linting and coverage analysis only in the latest Node version)
> [chore] Improve address verification unit tests

- package-lock.json
CI is failing due to a [vulnerability](https://github.com/EasyPost/easypost-node/security/dependabot/53) from express.js. This has been patch by running `npm audit fix`
> fix CI build

- CHANGELOG.md
- src/services/billing_service.js
- test/services/billing.test.js
Newer payment method objects have `pm_` prefixes for their IDs rather than `card_` or `bank_`, meaning we can no longer rely on the prefix to determine the payment method type (to determine the endpoint needed for funding and deleting a payment method).
This now falls back to the `object` key ("CreditCard" or "BankAccount") to determine the payment method type.
- Unit tests for funding and deleting payment methods are mocked, so we can't test this E2E.
- Add unit test to confirm switch-case working for type determination when prefix is `pm_`
> [bug] Cannot determine payment method when funding/deleting

- .github/workflows/ci.yml
- audit-ci.jsonc
- Add Node 22 to CI compatibility matrix
- Test all Node versions, not just LTS
- Suppress warning for transitive vulnerability: https://github.com/advisories/GHSA-grv7-fg5c-xmjg
> [chore] Add Node 22 check to CI

- types/Shipment/Rate.d.ts
- types/index.d.ts
Some left over types where still being included and tsc would not build. This simply removes them.
No tests were affected
Please let me know if there is anything else left to do to complete your process. Thanks!
> chore: remove Carbon Offset types

- CHANGELOG.md
- Makefile
- src/constants.js
- src/services/carrier_account_service.js
- test/cassettes/CarrierAccount-Service_2076435725/creates-a-UPS-carrier-account_3537134608/recording.har
- test/cassettes/CarrierAccount-Service_2076435725/creates-a-carrier-account-with-a-custom-workflow_416546097/recording.har
- test/cassettes/CarrierAccount-Service_2076435725/creates-a-carrier-account_2088010306/recording.har
- test/cassettes/CarrierAccount-Service_2076435725/updates-a-UPS-carrier-account_2425174955/recording.har
- test/cassettes/CarrierAccount-Service_2076435725/updates-a-carrier-account_2644332837/recording.har
- test/services/carrier_account.test.js
- Routes `UpsAccount`, `UpsMailInnovationsAccount`, and `UpsSurepostAccount` create/update requests to the new `/ups_oauth_registrations` endpoint
Adds new tests for each, updates previous custom workflow test to use FedEx instead of UPS
> feat: Account for new UPS endpoint in carrier account create/update functions

- .mocharc.json
- package-lock.json
- package.json
This adds support for environment variables in the `.env` when running tests, and adds a `mocharc.json` file to hold the mocha commands. 
I just added a requirement on the `dotenv` package, the standard Node.js package for reading .env files, and moved the command line flags from the package.json into a mocharc.json file.
This solves the issues of like:
- Its been months since I worked on this, what were my API keys again?
- I need to pass 3 env variables to the tests, and now my command is like 3 lines tall in the terminal
Also fixes the repl command, since that was pointing to a file that didn't exist.
This is a change to the testing suite itself, so if the tests pass, this is tested, I guess?
> Cleans up tests a little bit

- README.md
- src/easypost.js
- src/models/claim.js
- src/services/base_service.js
- src/services/claim_service.js
- test/cassettes/BetaRateService_784563276/retrieve-invalid-lowest-rate_1308734214/recording.har
- test/cassettes/BetaRateService_784563276/retrieve-the-lowest-rate_1860369698/recording.har
- test/cassettes/BetaRateService_784563276/retrieves-a-list-of-stateless-rates_708839575/recording.har
- test/cassettes/BetaReferralCustomerService_312890993/Refund-a-payment-by-a-payment-log-ID_834598297/recording.har
- test/cassettes/BetaReferralCustomerService_312890993/Refund-by-amount-for-a-recent-payment_2095459785/recording.har
- test/cassettes/Claim-Service_1417924316/cancels-a-standalone-claim_1710270578/recording.har
- test/cassettes/Claim-Service_1417924316/creates-a-claim-object_2101092128/recording.har
- test/cassettes/Claim-Service_1417924316/retrieves-a-claim-object_3414227044/recording.har
- test/cassettes/Claim-Service_1417924316/retrieves-all-claim-objects_2221815381/recording.har
- test/cassettes/Claim-Service_1417924316/retrieves-next-page-of-claims_131645032/recording.har
- test/helpers/fixture.js
- test/services/claim.test.js
- types/Claim/Claim.d.ts
- types/Claim/ClaimCreateParameters.d.ts
- types/Claim/ClaimHistory.d.ts
- types/Claim/ClaimPaymentMethod.d.ts
- types/Claim/ClaimType.d.ts
- types/Claim/index.d.ts
Creates the model, service, tests, and types for the claims API.
Also fixes a minor issue with the beta APIs where it added two slashes, making it like `//beta/whatever`
Adds new tests based off the existing insurance tests
> Adds support for claims API

- CHANGELOG.md
- src/utils/util.js
- test/helpers/fixture.js
- test/services/webhook.test.js
When the `weight` field is present on a webhook (eg: tracking update), it gets converted but JS drops the decimal if `.0` which often is the case. This breaks webhook validation because HMAC signatures won't match if it's altered at all. This properly puts back the `.0` if necessary and missing to ensure that validation will continue to work. Tests validate that we properly compare the signatures
> fix: webhook validation when float weight field is present (closes #467)

- package-lock.json
- src/easypost.js
- src/services/api_key_service.js
- src/services/carrier_account_service.js
- src/services/referral_customer_service.js
- src/utils/util.js
- test/helpers/common.js
- test/helpers/fixture.js
- webpack.config.babel.js
Vulnerabilities are fixed with this PR.
Something was also complaining about a few straggling requires so I swapped them for import to make the build pass.
> chore: bump dependencies

- test/cassettes/Shipment-Service_2987889512/buys-a-shipment-with-end_shipper_id_3098977158/recording.har
- test/services/shipment.test.js
- types/Shipment/Shipment.d.ts
- Fix outdated TypeScript definition for Shipment buy function, account for EndShipper ID
- Fix unit test for Shipment buy with EndShipper that wasn't passing variables properly
Closes #478 
- Re-recorded cassette for Shipment buy with EndShipper
> [fix] Outdated TypeScript definition for Shipment buy function

- CHANGELOG.md
- index.js
- package-lock.json
- package.json
- src/easypost.js
- test/node_compatibility/index.js
- test/services/easypost.test.js
- Replaces Webpack with Vite for building the distributable library
- Fixes the filename for the `AddressCreateParameters` type declaration file (closes #487)
- Bumps dependencies
> chore: prep v7.5.4 for release

- CHANGELOG.md
- audit-ci.jsonc
- package-lock.json
- package.json
- src/services/webhook_service.js
- test/cassettes/Webhook-Service_1674309497/creates-a-webhook_1900246512/recording.har
- test/cassettes/Webhook-Service_1674309497/updates-a-webhook_1079406087/recording.har
- test/helpers/fixture.js
- test/helpers/setup_polly.js
- test/services/webhook.test.js
- types/Webhook/Webhook.d.ts
- types/Webhook/WebhookCreateParameters.d.ts
- Adds `secret` and `custom_headers` properties to Typescript definitions of a Webhook
- Bumps deps to fix vulnerability
- Tests webhook params
> fix: wrap params for update webhook function

- test/cassettes/Error-Service_386538342/pulls-out-error-properties-of-an-API-error-when-using-the-alternative-format_650479431/recording.har
- test/services/address.test.js
- test/services/error.test.js
Adds tests for alternative error format and address verification errors to ensure they work correctly
> test: alternative error format

- CHANGELOG.md
- package-lock.json
- src/services/beta_referral_customer_service.js
- src/services/referral_customer_service.js
- test/cassettes/BetaReferralCustomerService_312890993/returns-a-client-secret-for-bank-accounts_845792627/recording.har
- test/cassettes/BetaReferralCustomerService_312890993/returns-a-client-secret-for-credit-cards_1367228089/recording.har
- test/cassettes/ReferralCustomer-Service_3380152635/raises-an-error-when-adding-a-bank-account-from-Stripe-fails_3043649864/recording.har
- test/cassettes/ReferralCustomer-Service_3380152635/raises-an-error-when-adding-a-credit-card-from-Stripe-fails_4230750010/recording.har
- test/helpers/fixture.js
- test/services/beta_referral_customer.test.js
- test/services/referral_customer.test.js
- Adds the following functions to assist ReferralCustomers add credit cards and bank accounts:
- `betaReferralCustomer.createCreditCardClientSecret`
- `betaReferralCustomer.createBankAccountClientSecret`
- `referralCustomer.addCreditCardFromStripe`
- `referralCustomer.addBankAccountFromStripe`
- Properly returns the response body of the following functions: `addPaymentMethod`, `refundByAmount`, `refundByPaymentLog`
- Adds new tests for functions
> feat: new billing functions for referral customers

- CHANGELOG.md
- src/constants.js
- src/services/carrier_account_service.js
- test/cassettes/CarrierAccount-Service_2076435725/creates-an-Amazon-carrier-account_772644036/recording.har
- test/services/carrier_account.test.js
> feat: route Amazon account on create

- index.js
- package.json
- vite.config.js
This adds an ESM build alongside a CJS build, so projects that are not CJS or are `"type": "module"` can use the project now.
I believe this should fix #446
I made a separate Next.js 15 app and tried to install and use the project. I confirmed that it did not work. After these changes, it started working. 
> Makes esm and cjs build

- CHANGELOG.md
- src/models/tracker.js
- types/Tracker/Tracker.d.ts
- types/Tracker/TrackingDetail.d.ts
> feat: add missing tracker props

- CHANGELOG.md
- UPGRADE_GUIDE.md
- package.json
> chore: prep v8.0.0 for release

- package.json
v8.0 removed the "repl" script, but it's still referenced in the `bin` section of package.json.  `pnpm` complains about this when installing.
```
 WARN  Failed to create bin at /Users/dimfeld/.pnpm/5/.pnpm/@easypost+api@file+..+..+Documents+src+easypost-node_461784133dc0ee17d7247d322e58791e/node_modules/@easypost/api/node_modules/.bin/easypost. ENOENT: no such file or directory, open '/Users/dimfeld/.pnpm/5/.pnpm/@easypost+api@file+..+..+Documents+src+easypost-node_461784133dc0ee17d7247d322e58791e/node_modules/@easypost/api/repl.js'
 WARN  Failed to create bin at /Users/dimfeld/Library/pnpm/easypost. ENOENT: no such file or directory, open '/Users/dimfeld/.pnpm/5/.pnpm/@easypost+api@file+..+..+Documents+src+easypost-node_461784133dc0ee17d7247d322e58791e/node_modules/@easypost/api/repl.js' …
```
> Remove bin entry from package.json for removed "repl" script

- CHANGELOG.md
- package-lock.json
- package.json
- src/constants.js
- src/services/carrier_account_service.js
- test/cassettes/CarrierAccount-Service_2076435725/creates-a-UPS-carrier-account_3537134608/recording.har
- test/cassettes/CarrierAccount-Service_2076435725/updates-a-UPS-carrier-account_2425174955/recording.har
- test/cassettes/CarrierAccount-Service_2076435725/updates-a-carrier-account_2644332837/recording.har
> fix: endpoint used for UPS create/update
